### ISSUE TITLE
Suggestion: load Ayat & prayer time in background

### ISSUE THREAD

**Issue by adityaputra** [hasanhameed07/ayat-today#1]
Jazakallahu khairan for this beautiful app. I like to use this chrome app but sometimes I feel that the ayat is too slow to load. Every time I open a new tab, I would need to wait around 3-5s until the ayat appears. I think we can make a mechanism where the ayat will be loaded in the background; or perhaps we can load multiple ayat at once so the user don't need to wait for ayat loading everytime he opens a new tab. Same thing goes with prayer times. 

If anyone knows what to change on the code, I will be more than happy to alter the code and make a PR.
Thanks again.

**Comment by hasanhameed-iomechs** [comment]
Thanks Aditya, it depends on the net speed of course but your suggestion can be implemented and we will work on it.
