### ISSUE TITLE
Word-by-Word translation feature

### ISSUE THREAD

**Issue by hasanhameed07** [hasanhameed07/ayat-today#5]
Allow users to view the translation of a word when hover, like in quran.com

**Comment by AhsanAyaz** [comment]
For this one, you might want to use Google Translate API. Or [Yandex](https://yandex.com/dev/translate/). Have a look and we can proceed further.

**Comment by hasanhameed07** [comment]
@AhsanAyaz thanks for the suggestion. 

I found this API for correct Word by word translation.
http://api.alquran.cloud/v1/ayah/262/editions/quran-wordbyword

Just need to parse the response and apply a regular expression.
